// app/layout.js

import { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { UserSettingsProvider } from "@/5_entities/user";
import { ToastProvider } from "@/6_shared";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  // Setting up default theme and preventing flickering
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme")?.value || "dark"; // Zadana vrijednost je 'dark'

  return (
    <html lang="en" className={theme}>
      {/*_PREVENTING USER FROM ZOOMING_*/}
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
      />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative w-100% h-dvh overflow-auto bg-background`}
      >
        <UserSettingsProvider>
          <ToastProvider>
            {children}
            <div id="portal-root"></div>
            <div id="toast-root"></div>
          </ToastProvider>
        </UserSettingsProvider>
      </body>
    </html>
  );
}
